version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://postgres:password@db:5432/restaurant?schema=public
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run dev

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: